### ISSUE TITLE
Cake v Sake

### ISSUE THREAD

**Issue by mishfit** [sakeproject/sake#20]
Are there differences in what sake and [cake](http://cakebuild.net/) are trying to accomplish? Also, is this pronounced sake (as in, "for goodness sakes") or saké?

_not really an issue, but I couldn't think of a better way to ask the question_

**Comment by jeffogata** [comment]
I pronounce it Sake, rhymes with "make".  My reasoning is that Sake makes use of the Spark view engine, so I believe it is a shortening of "spark make".  Also, psake (powershell make) is pronounced like the Japanese rice wine, and I use that at work so it would be confusing to pronounce them both the same way.

**Comment by mishfit** [comment]
Cool, just wondering
